# Generated by Django 4.0 on 2021-12-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Data',
            fields=[
                ('usn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others'), ('Animals', 'Animals')], default=1, max_length=50)),
                ('course', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Student_Data',
                'verbose_name_plural': 'Student_Datas',
            },
        ),
    ]
