# Generated by Django 4.0 on 2021-12-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update_Delete',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('susn', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('sage', models.IntegerField()),
                ('sgender', models.CharField(max_length=50)),
                ('scourse', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Update_Delete',
                'verbose_name_plural': 'Update_Deletes',
            },
        ),
    ]
